### ISSUE TITLE
Lambda function is not configured to use the latest runtime version

### ISSUE THREAD

**Issue by dwaraplk** [aws-samples/aws-insurancelake-infrastructure#1]
Hi,

I have tried deploying this sample and got this error, can you pls check and let us know
[Error at /Dev-InsuranceLakeEtlPipeline/Dev/InsuranceLakeEtlStepFunctions/DevInsuranceLakeEtlStatusUpdate/Resource] AwsSolutions-L1: The non-container Lambda function is not configured to use the latest runtime version.

**Comment by coryvisi** [comment]
Thank you for your interest in InsuranceLake!

This is a known issue with cdk-nag/aws-cdk being tracked here: https://github.com/aws/aws-cdk/issues/26451 

For a quick workaround, I recommend temporarily limiting the `aws-cdk-lib` version in your `requirements.txt` as follows:
```
# Python 3.12 was introduced in 2.107 but is not GA yet and confuses CDK-nag checks
aws-cdk-lib<=2.106.1
```

Note that this would replace the existing aws-cdk-lib line, and would require re-installing the libraries in your virtual environment.

Alternatively, you can add a suppression as the contributor in the issue above suggests.

I do plan to fix this in the codebase, and I'm ok with leaving this ticket open until that happens.

Please let us know if this resolved your issue and if you have any other questions.

**Comment by dwaraplk** [comment]
Thank you coryvisi. I appreciate the quick workaround solution, I will explore it and get back to you.

**Comment by coryvisi** [comment]
This issue has been addressed in commit: https://github.com/aws-samples/aws-insurancelake-infrastructure/commit/b3b88a3c6dc4cbff0ccac765d48fe779168dd00d 
We plan to pin the aws-cdk-lib version until Python 3.12 is GA or an improvement to the Python runtime checks becomes available in CDK-nag.
